/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.billingSystem.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.billingSystem.controller.ControllerFactory;
import lk.ijse.billingSystem.controller.custom.BatchController;
import lk.ijse.billingSystem.controller.custom.CourseController;
import lk.ijse.billingSystem.controller.custom.PaymentController;
import lk.ijse.billingSystem.controller.custom.Reg_CourseController;
import lk.ijse.billingSystem.controller.custom.RegistrationController;
import lk.ijse.billingSystem.controller.custom.StudentController;
import lk.ijse.billingSystem.dto.BatchDTO;
import lk.ijse.billingSystem.dto.CourseDTO;
import lk.ijse.billingSystem.dto.PaymentDTO;
import lk.ijse.billingSystem.dto.Reg_CourseDTO;
import lk.ijse.billingSystem.dto.StudentDTO;

/**
 *
 * @author DEll
 */
public class CourseRegistration extends javax.swing.JFrame {

    StudentController studentController = (StudentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.STUDENT);
    RegistrationController registrationController = (RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
    BatchController batchController = (BatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BATCH);
    CourseController courseController = (CourseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.COURSE);
    PaymentController paymentController = (PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PAYMENT);
    Reg_CourseController reg_CourseController = (Reg_CourseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REG_COURSE);

    /**
     * Creates new form PaymentForm
     */
    public CourseRegistration() {
        initComponents();
        loadDate();
        loadTime();
        loadCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        jSeparator9 = new javax.swing.JSeparator();
        cmbNewCourse = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cmbNewBranch = new javax.swing.JComboBox();
        txtNewBatch = new javax.swing.JTextField();
        txtNewCourse = new javax.swing.JTextField();
        txtNewCid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbNewBatch = new javax.swing.JComboBox();
        pnlNewCourse = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        cmbNewCourse1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        cmbNewBranch1 = new javax.swing.JComboBox();
        txtNewBatch1 = new javax.swing.JTextField();
        txtNewCourse1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNewCid1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbNewBatch1 = new javax.swing.JComboBox();
        pnlPayment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sepRid = new javax.swing.JSeparator();
        txtRID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtAmount = new javax.swing.JTextField();
        btnFinish = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtNIC = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtNBalance = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtRecievedAMount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sepName = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        jSeparator6 = new javax.swing.JSeparator();
        rbtnInstall = new javax.swing.JRadioButton();
        rbtnNew = new javax.swing.JRadioButton();
        txtRCID = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtCourseFee = new javax.swing.JTextField();
        txtNewRCID = new javax.swing.JTextField();
        txtDueDate = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtPaidFromFee = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 140, 10));

        cmbNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewCourseActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 140, 30));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 140, 30));

        cmbNewBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Panadura", "Galle" }));
        cmbNewBranch.setSelectedIndex(-1);
        cmbNewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewBranchActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNewBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, 30));
        getContentPane().add(txtNewBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 50, -1));
        getContentPane().add(txtNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 70, -1));
        getContentPane().add(txtNewCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Course");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Branch");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Batch");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, 30));

        cmbNewBatch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNewBatchItemStateChanged(evt);
            }
        });
        cmbNewBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewBatchActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNewBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 30));

        pnlNewCourse.setBackground(new java.awt.Color(255, 255, 255));
        pnlNewCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlNewCourse.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 140, 10));

        cmbNewCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewCourse1ActionPerformed(evt);
            }
        });
        pnlNewCourse.add(cmbNewCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Balance");
        pnlNewCourse.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 140, 30));

        jTextField2.setBorder(null);
        pnlNewCourse.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 140, 30));

        cmbNewBranch1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Panadura", "Galle" }));
        cmbNewBranch1.setSelectedIndex(-1);
        cmbNewBranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewBranch1ActionPerformed(evt);
            }
        });
        pnlNewCourse.add(cmbNewBranch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, 30));
        pnlNewCourse.add(txtNewBatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 50, -1));
        pnlNewCourse.add(txtNewCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Course");
        pnlNewCourse.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 30));
        pnlNewCourse.add(txtNewCid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 50, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Batch");
        pnlNewCourse.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Branch");
        pnlNewCourse.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 140, 30));

        cmbNewBatch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNewBatch1ItemStateChanged(evt);
            }
        });
        cmbNewBatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewBatch1ActionPerformed(evt);
            }
        });
        pnlNewCourse.add(cmbNewBatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 30));

        getContentPane().add(pnlNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 720, 120));

        pnlPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 193, 161));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Payment");
        jLabel1.setOpaque(true);
        pnlPayment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Registration No");
        pnlPayment.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 140, 30));
        pnlPayment.add(sepRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 120, 10));

        txtRID.setBorder(null);
        pnlPayment.add(txtRID, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Amount");
        pnlPayment.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Balance Amount");
        pnlPayment.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Received Amount");
        pnlPayment.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 140, 30));
        pnlPayment.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 180, -1));

        txtAmount.setBorder(null);
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        pnlPayment.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 180, 30));

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        pnlPayment.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("NIC");
        pnlPayment.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));
        pnlPayment.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, 10));

        txtNIC.setBorder(null);
        pnlPayment.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, 30));
        pnlPayment.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 630, 180, 10));

        txtNBalance.setBorder(null);
        pnlPayment.add(txtNBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 180, 30));
        pnlPayment.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 180, -1));

        txtRecievedAMount.setBorder(null);
        txtRecievedAMount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecievedAMountActionPerformed(evt);
            }
        });
        pnlPayment.add(txtRecievedAMount, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Name");
        pnlPayment.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));
        pnlPayment.add(sepName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 390, 10));

        txtName.setBorder(null);
        pnlPayment.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 390, 30));
        pnlPayment.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1000, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Type");
        pnlPayment.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 140, 30));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full", "Half" }));
        cmbType.setSelectedIndex(-1);
        cmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTypeItemStateChanged(evt);
            }
        });
        pnlPayment.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 30));
        pnlPayment.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1000, 20));

        btnGroupType.add(rbtnInstall);
        rbtnInstall.setText("Registered");
        rbtnInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInstallActionPerformed(evt);
            }
        });
        pnlPayment.add(rbtnInstall, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btnGroupType.add(rbtnNew);
        rbtnNew.setText("New");
        rbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNewActionPerformed(evt);
            }
        });
        pnlPayment.add(rbtnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        pnlPayment.add(txtRCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 50, 30));

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-search-30.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        pnlPayment.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 174, 30, 40));
        pnlPayment.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 180, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Tax");
        pnlPayment.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 140, 30));

        txtTax.setBorder(null);
        pnlPayment.add(txtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 180, 30));
        pnlPayment.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 180, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Due Date");
        pnlPayment.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 140, 30));

        txtDiscount.setBorder(null);
        pnlPayment.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 180, 30));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-home-55.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        pnlPayment.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 50));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-minimize-window-48.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        pnlPayment.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 40));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-close-window-48.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        pnlPayment.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 51, 102));
        pnlPayment.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 30));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 51, 102));
        pnlPayment.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 30));

        txtCourseFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseFeeActionPerformed(evt);
            }
        });
        pnlPayment.add(txtCourseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, 90, -1));

        txtNewRCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRCIDActionPerformed(evt);
            }
        });
        pnlPayment.add(txtNewRCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 50, 30));

        txtDueDate.setBorder(null);
        pnlPayment.add(txtDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 180, 30));
        pnlPayment.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 680, 180, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Discount");
        pnlPayment.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 140, 30));
        pnlPayment.add(txtPaidFromFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 60, -1));
        pnlPayment.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 60, -1));

        getContentPane().add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (rbtnInstall.isSelected()) {
            paymentRegisteredCourse();
            clearText();
        } else if (rbtnNew.isSelected()) {
            try {
                Reg_CourseDTO reg_CourseDTO = new Reg_CourseDTO(txtRID.getText(), Integer.parseInt(txtNewCid.getText()), Integer.parseInt(txtNewBatch.getText()));
                boolean isAdded = reg_CourseController.addReg_Course(reg_CourseDTO);

                
                int rcid = reg_CourseController.searchRCID(txtRID.getText(), Integer.parseInt(txtNewCid.getText()), Integer.parseInt(txtNewBatch.getText()));
                txtNewRCID.setText(Integer.toString(rcid));

                if (rcid!=0) {
                    paymentNewCourse();
                    clearText();
                }
            } catch (Exception ex) {
                Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinishActionPerformed

    private void rbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNewActionPerformed
        txtRCID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNewActionPerformed

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-search-40.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-search-30.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        lblSearch.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-search-40.png"));
        String nic = txtNIC.getText();
        try {
            StudentDTO studentDTO = studentController.searchStudent(nic);
            txtName.setText(studentDTO.getName());
            txtRID.setText(studentDTO.getRid());
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));
        Main m = new Main();
        this.setVisible(false);
        m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-55.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
        this.setExtendedState(ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit?");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseExited

    private void rbtnInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInstallActionPerformed
        //pnlInstall.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtnInstallActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void cmbNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewCourseActionPerformed
        try {

            String course = (String) cmbNewCourse.getSelectedItem();
            if (course != null) {
                CourseDTO courseDTO = courseController.searchCourse(course);
                txtNewCid.setText(Integer.toString(courseDTO.getCid()));
                txtNewCourse.setText(course);

//                txtFee.setText(Double.toString(courseDTO.getRegFee()));
//                double nbt = Double.parseDouble(courseDTO.getTax());
//                double regFee = courseDTO.getRegFee();
//                double tax = regFee / 100 * nbt;
//                int cid = Integer.parseInt(txtCid.getText());
//                txtNbt.setText(Double.toString(tax));
//                txtAmount.setText(Double.toString(regFee + tax));
//                String branch = txtBranchName.getText();
//                if (branch != null || cid != 0) {
//                    loadBatches(branch, cid);
//                } else {
//                    System.out.println("null");
//                }
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewCourseActionPerformed

    private void cmbNewBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewBatchActionPerformed

    }//GEN-LAST:event_cmbNewBatchActionPerformed

    private void cmbNewBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewBranchActionPerformed
        String branch = (String) cmbNewBranch.getSelectedItem();

        int cid = Integer.parseInt(txtNewCid.getText());
        loadBatches(branch, cid);

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewBranchActionPerformed

    private void cmbNewBatchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNewBatchItemStateChanged
        try {
            String batch = (String) cmbNewBatch.getSelectedItem();
            BatchDTO batchDTO = batchController.searchBatch(batch);
            txtNewBatch.setText(Integer.toString(batchDTO.getBid()));
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbNewBatchItemStateChanged

    private void cmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTypeItemStateChanged
        try {
            if (rbtnInstall.isSelected()) {
                int rcid = reg_CourseController.searchRCID(txtRID.getText(), Integer.parseInt(txtNewCid.getText()), Integer.parseInt(txtNewBatch.getText()));
                txtRCID.setText(Integer.toString(rcid));
                System.out.println(rcid);
            } else {
                txtRCID.setText("");
            }

            if (cmbType.getSelectedItem() == "Full") {
                fullpayment();
            } else if (cmbType.getSelectedItem() == "Half") {
                halfPayment();
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbTypeItemStateChanged

    private void txtCourseFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseFeeActionPerformed

    private void txtNewRCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRCIDActionPerformed

    private void txtRecievedAMountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecievedAMountActionPerformed
        double ra=Double.parseDouble(txtRecievedAMount.getText());
        double nbalance=ra-Double.parseDouble(txtAmount.getText());
        txtNBalance.setText(Double.toString(nbalance));
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecievedAMountActionPerformed

    private void cmbNewCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewCourse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewCourse1ActionPerformed

    private void cmbNewBranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewBranch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewBranch1ActionPerformed

    private void cmbNewBatch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNewBatch1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewBatch1ItemStateChanged

    private void cmbNewBatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewBatch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewBatch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JComboBox cmbNewBatch;
    private javax.swing.JComboBox cmbNewBatch1;
    private javax.swing.JComboBox cmbNewBranch;
    private javax.swing.JComboBox cmbNewBranch1;
    private javax.swing.JComboBox cmbNewCourse;
    private javax.swing.JComboBox cmbNewCourse1;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlNewCourse;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JRadioButton rbtnInstall;
    private javax.swing.JRadioButton rbtnNew;
    private javax.swing.JSeparator sepName;
    private javax.swing.JSeparator sepRid;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCourseFee;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtNBalance;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewBatch;
    private javax.swing.JTextField txtNewBatch1;
    private javax.swing.JTextField txtNewCid;
    private javax.swing.JTextField txtNewCid1;
    private javax.swing.JTextField txtNewCourse;
    private javax.swing.JTextField txtNewCourse1;
    private javax.swing.JTextField txtNewRCID;
    private javax.swing.JTextField txtPaidFromFee;
    private javax.swing.JTextField txtRCID;
    private javax.swing.JTextField txtRID;
    private javax.swing.JTextField txtRecievedAMount;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTax;
    // End of variables declaration//GEN-END:variables

    private void loadDate() {
        Date date = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        String dateFormat = sf.format(date);
        lblDate.setText(dateFormat);
    }

    private void loadTime() {
        new javax.swing.Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss ");
                String DateFormat = df.format(d1);
                lblTime.setText(DateFormat);
            }
        }).start();
    }

    private void loadCourses() {
        cmbNewBatch.removeAllItems();
        try {
            ArrayList<CourseDTO> alCourses = courseController.getCourses();
            for (CourseDTO course : alCourses) {
                cmbNewCourse.addItem(course.getName());
                cmbNewCourse.setSelectedIndex(-1);
            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void loadBatches(String branch, int cid) {
        cmbNewBatch.removeAllItems();
        try {
            ArrayList<BatchDTO> alBatches = batchController.getBatches(branch, cid);

            for (BatchDTO Batch : alBatches) {
                cmbNewBatch.addItem(Batch.getName());
                System.out.println(Batch.getName());
            }

        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void fullpayment() {
        try {
            CourseDTO courseDTO = courseController.searchCourse((String) cmbNewCourse.getSelectedItem());
            double cFee = courseDTO.getFee();
            txtCourseFee.setText(Double.toString(cFee));
            double nbt = Double.parseDouble(courseDTO.getTax());
            double fee = courseDTO.getFee();
            txtPaidFromFee.setText(Double.toString(fee));
            double tax = fee / 100 * nbt;
            txtTax.setText(Double.toString(tax));
            double dicount = Double.parseDouble(courseDTO.getDiscount());
            double dis = fee / 100 * dicount;
            txtTax.setText(Double.toString(tax));
            txtDiscount.setText(Double.toString(dis));
            txtPaidFromFee.setText(Double.toString(fee));
            txtAmount.setText(Double.toString(fee - dis + tax));
            txtState.setText("Paid");
            
//            Date date2=null;
//            SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");
//            String d=sf.format(date2);
//            txtDueDate.setText(d);
//            System.out.println(d);
            
            txtDueDate.setText("-");
            
            
//            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
//        String dateInString = "00-00-0000";
//
//
//            Date date = formatter.parse(dateInString);
//            System.out.println(date);
//            System.out.println(formatter.format(date));

            
//            Date date2 = new java.util.Date(0,0,0);
//            SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");
//            String d=sf.format(date2);
//            txtDueDate.setText(d);
//            String n=txtDueDate.getText();
//            System.out.println(n);
        
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void halfPayment() {
        try {
            CourseDTO courseDTO = courseController.searchCourse((String) cmbNewCourse.getSelectedItem());
            
            String duration=courseDTO.getDuration();
            //calDate(duration);
//            
//            String[] sep = duration.split(" ");
//            System.out.println(sep[1]);
//            if ("Months".equals(sep[1])) {
//                int x = Integer.parseInt(sep[0]);
//                int y = x / 2;
//
//                String sDate1 = lblDate.getText();
//                Date pDate = new SimpleDateFormat("dd-MM-yyyy").parse(sDate1);
//
//                Calendar c = Calendar.getInstance();
//                c.setTime(pDate);
//                c.add(Calendar.MONTH, y);
//                Date newDate = c.getTime();
//                
//                Date d1 = newDate;
//                SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
//                String d = sf.format(d1);
//                txtDueDate.setText(d);
//                
//                System.out.println(d);
//
//            }else if("Days".equals(sep[1])) {
//            int x = Integer.parseInt(sep[0]);
//            int y = x / 2;
//            
//            String sDate1 = lblDate.getText();
//                Date date1 = new SimpleDateFormat("dd-MM-yyyy").parse(sDate1);
//            
//            Calendar c = Calendar.getInstance();
//                c.setTime(date1);
//                c.add(Calendar.DATE, y);
//                Date newDate = c.getTime();
//                
//                Date d1 = newDate;
//                SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
//                String d = sf.format(d1);
//                txtDueDate.setText(d);
//                
//                System.out.println(d);
//            }
//
//
            BatchDTO batchDTO = batchController.searchBatch((String) cmbNewBatch.getSelectedItem());
            Date d=batchDTO.getInstall_Date();
            SimpleDateFormat sf=new SimpleDateFormat("dd-MM-yyyy");
            String date=sf.format(d);
            txtDueDate.setText(date);
            
            
            double cFee = courseDTO.getFee();
            txtCourseFee.setText(Double.toString(cFee));
            double nbt = Double.parseDouble(courseDTO.getTax());
            double fee = courseDTO.getFee() / 2;
            txtPaidFromFee.setText(Double.toString(fee));
            double tax = fee / 100 * nbt;
            txtTax.setText(Double.toString(tax));
            txtTax.setText(Double.toString(tax));
            txtDiscount.setText("0");
            txtAmount.setText(Double.toString(fee + tax));
            txtState.setText("Install");
            
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void paymentRegisteredCourse() {
        try {
            CourseDTO courseDTO = courseController.searchCourse(txtNewCourse.getText());

            Double courseFee = courseDTO.getFee();
            String p = txtCourseFee.getText();
            double paid = Double.parseDouble(p);
            double c = courseDTO.getFee();
            double balance = (c - paid);

            System.out.println(Double.parseDouble(txtTax.getText()));
            System.out.println(Double.parseDouble(txtDiscount.getText()));
            System.out.println(paid);
            System.out.println(balance);

            String sDate1 = lblDate.getText();
            Date pDate = new SimpleDateFormat("dd-MM-yyyy").parse(sDate1);
//            String sDate2 = txtDueDate.getText();
//            Date dueDate = new SimpleDateFormat("dd-MM-yyyy").parse(sDate2);
//            
            //PaymentDTO paymentDTO = new PaymentDTO(pDate, Double.parseDouble(txtTax.getText()), Double.parseDouble(txtDiscount.getText()), Double.parseDouble(txtPaidFromFee.getText()),Double.parseDouble(txtAmount.getText()), balance, Integer.parseInt(txtRCID.getText()));
            Reg_CourseDTO reg_CourseDTO=new Reg_CourseDTO(Integer.parseInt(txtRCID.getText()), balance, txtState.getText());





System.out.println("1111111111111111111");
            System.out.println(Integer.parseInt(txtRCID.getText()));
            System.out.println(txtRID.getText());
            System.out.println(Integer.parseInt(txtNewCid.getText()));
            System.out.println(Integer.parseInt(txtNewBatch.getText()));
            System.out.println(balance);
            System.out.println(txtState.getText());
            boolean update=reg_CourseController.update(reg_CourseDTO);
            //boolean isAdded = paymentController.AddPayment(paymentDTO, reg_CourseDTO);
            if (update) {
                JOptionPane.showMessageDialog(this, "Payment has been Successfully Added");
            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been Successfully Added");
            }



//            boolean isAdded = paymentController.AddPayment(paymentDTO, reg_CourseDTO);
//            if (isAdded) {
//                JOptionPane.showMessageDialog(this, "Payment has been Successfully Added");
//            } else {
//                JOptionPane.showMessageDialog(this, "Payment hasn't been Successfully Added");
//            }
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void paymentNewCourse() {
        try {
            CourseDTO courseDTO = courseController.searchCourse(txtNewCourse.getText());
            
            double courseFee = courseDTO.getFee();
//            String p = txtCourseFee.getText();
//            double paid = Double.parseDouble(p);
//            double c = courseDTO.getFee();
            
            double balance = (courseFee - Double.parseDouble(txtPaidFromFee.getText()));

            System.out.println("Tax "+Double.parseDouble(txtTax.getText()));
            System.out.println("discount "+Double.parseDouble(txtDiscount.getText()));
            System.out.println("balance "+balance);
            System.out.println("Amount "+Double.parseDouble(txtAmount.getText()));

//            if (cmbType.getSelectedItem().equals("Full")) {
//                            PaymentDTO paymentDTO = new PaymentDTO(pDate, Double.parseDouble(txtTax.getText()), Double.parseDouble(txtDiscount.getText()), Double.parseDouble(txtAmount.getText()), balance, dueDate, Integer.parseInt(txtNewRCID.getText()));
//
//            }
            String sDate1 = lblDate.getText();
            Date pDate = new SimpleDateFormat("dd-MM-yyyy").parse(sDate1);
            String sDate2 = txtDueDate.getText();
            Date dueDate = new SimpleDateFormat("dd-MM-yyyy").parse(sDate2);
            
            PaymentDTO paymentDTO = new PaymentDTO(pDate, Double.parseDouble(txtTax.getText()), Double.parseDouble(txtDiscount.getText()), Double.parseDouble(txtPaidFromFee.getText()),Double.parseDouble(txtAmount.getText()), balance, Integer.parseInt(txtNewRCID.getText()));
            Reg_CourseDTO reg_CourseDTO=new Reg_CourseDTO(Integer.parseInt(txtNewRCID.getText()), balance, txtState.getText());
            System.out.println("1111111111111111111");
            System.out.println(Integer.parseInt(txtNewRCID.getText()));
            System.out.println(txtRID.getText());
            System.out.println(Integer.parseInt(txtNewCid.getText()));
            System.out.println(Integer.parseInt(txtNewBatch.getText()));
            System.out.println(balance);
            System.out.println(txtState.getText());
            boolean update=reg_CourseController.update(reg_CourseDTO);
            //boolean isAdded = paymentController.AddPayment(paymentDTO, reg_CourseDTO);
            System.out.println(dueDate);
            if (update) {
                JOptionPane.showMessageDialog(this, "Payment has been Successfully Added");
            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been Successfully Added");
            }
        } catch (Exception ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void clearText(){
        txtAmount.setText("");
        txtCourseFee.setText("");
        txtDiscount.setText("");
        txtNIC.setText("");
        txtName.setText("");
        txtNewBatch.setText("");
        txtNewCid.setText("");
        txtNewCourse.setText("");
        txtNewRCID.setText("");
        txtRCID.setText("");
        txtRID.setText("");
        txtTax.setText("");
    }
    void calDate(String duration){
        
            String[] sep=duration.split(" ");
            System.out.println(sep[1]);
            if ("Months".equals(sep[1])) {
                int x=Integer.parseInt(sep[0]);
                int y=x/2;
                System.out.println(y);
                String date = lblDate.getText();
                String[] sd=date.split("-");
                
                    System.out.println(sd[1]);
                int curMonth=Integer.parseInt(sd[1]); 
                int dueMonth=curMonth+y;
                if (dueMonth>12) {
                    int year=Integer.parseInt(sd[2]);
                    int z=year+1;
                    int diff=dueMonth-12;
                    dueMonth=diff;
                    String newDate=sd[0]+"-"+diff+"-"+z;
                    txtDueDate.setText(newDate);
                }else{
                System.out.println(dueMonth);
                String newDate=sd[0]+"-"+dueMonth+"-"+sd[2];
                txtDueDate.setText(newDate);
                }
            }else if ("Days".equals(sep[1])) {
                int x=Integer.parseInt(sep[0]);
                int y=x/2;
                System.out.println(y);
                String date = lblDate.getText();
                String[] sd=date.split("-");
                
                    System.out.println(sd[1]);
                int curDay=Integer.parseInt(sd[0]); 
                int dueDay=curDay+y;
                if (dueDay>30) {
                    int month=Integer.parseInt(sd[1]);
                    int z=month+1;
                    int diff=dueDay-30;
                    System.out.println(diff);
                    String newDate=diff+"-"+z+"-"+sd[2];
                    txtDueDate.setText(newDate);
                }else{
                System.out.println(dueDay);
                String newDate=dueDay+"-"+sd[1]+"-"+sd[2];
                txtDueDate.setText(newDate);
                }
            }
    }
}
