/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.billingSystem.view;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.billingSystem.db.DBConnection;


/**
 *
 * @author DEll
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        lblRegister.setBackground(new Color(253, 254, 254, 150));
        lblPayment.setBackground(new Color(253, 254, 254, 150));
        lblBatchTransfer.setBackground(new Color(253, 254, 254, 150));
        lblIncome.setBackground(new Color(253, 254, 254, 150));
        lblPending.setBackground(new Color(253, 254, 254, 150));
        pnlNewAdmin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlNewAdmin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnAdd = new javax.swing.JButton();
        lblCloseA = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTransfer = new javax.swing.JLabel();
        lblRName = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblBatchTransfer = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblPending = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNewAdmin.setBackground(new java.awt.Color(255, 204, 204));
        pnlNewAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 2));
        pnlNewAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Admin Name");
        pnlNewAdmin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Password");
        pnlNewAdmin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Confirm Password");
        pnlNewAdmin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 20));

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, 30));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlNewAdmin.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 30));

        lblCloseA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/Error-icon.png"))); // NOI18N
        lblCloseA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseAMouseEntered(evt);
            }
        });
        pnlNewAdmin.add(lblCloseA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));
        pnlNewAdmin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 62, 180, 10));

        jPanel1.add(pnlNewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 340, 200));

        lblTransfer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTransfer.setForeground(new java.awt.Color(51, 51, 255));
        lblTransfer.setText("Batch Transfer");
        jPanel1.add(lblTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 170, 30));

        lblRName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRName.setForeground(new java.awt.Color(51, 51, 255));
        lblRName.setText("Register");
        jPanel1.add(lblRName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 130, 30));

        lblRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(51, 51, 255));
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-student-registration-100.png"))); // NOI18N
        lblRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblRegister.setOpaque(true);
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterMouseExited(evt);
            }
        });
        jPanel1.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 170, 200));

        lblBatchTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-transfer-filled-100.png"))); // NOI18N
        lblBatchTransfer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblBatchTransfer.setOpaque(true);
        lblBatchTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBatchTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBatchTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBatchTransferMouseExited(evt);
            }
        });
        jPanel1.add(lblBatchTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 170, 200));

        lblP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblP.setForeground(new java.awt.Color(51, 51, 255));
        lblP.setText("Payment");
        jPanel1.add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 130, 30));

        lblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-get-cash-100.png"))); // NOI18N
        lblPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblPayment.setOpaque(true);
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
        });
        jPanel1.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, 200));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/ijse-logo.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 24, 460, 120));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-shutdown-48.png"))); // NOI18N
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel1.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 50, 50));

        lblSettings.setBackground(new java.awt.Color(153, 255, 153));
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-services-48.png"))); // NOI18N
        lblSettings.setOpaque(true);
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });
        jPanel1.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 60, 60));

        lblIncome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(51, 51, 255));
        lblIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/reports.png"))); // NOI18N
        lblIncome.setText("Reports");
        lblIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblIncome.setOpaque(true);
        lblIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIncomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIncomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIncomeMouseExited(evt);
            }
        });
        jPanel1.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 190, 80));

        lblPending.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPending.setForeground(new java.awt.Color(51, 51, 255));
        lblPending.setText("Pending Payments");
        lblPending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblPending.setOpaque(true);
        lblPending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendingMouseExited(evt);
            }
        });
        jPanel1.add(lblPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 200, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/bg-nsit-areas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 900, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        RegistrationForm r = new RegistrationForm();
        this.setVisible(false);
        r.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        PaymentsForm p = new PaymentsForm();
        this.setVisible(false);
        p.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseEntered
        lblRegister.setSize(180, 210);
        lblRName.setForeground(Color.red);
//        Font font=new Font("Times New Roman", Font.BOLD, 14);
//        lblRName.setFont(font);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegisterMouseEntered

    private void lblRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseExited
        lblRegister.setSize(170, 200);
        lblRName.setForeground(new Color(51, 51, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegisterMouseExited

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered
        lblPayment.setSize(180, 210);
        lblP.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited
        lblPayment.setSize(170, 200);
        lblP.setForeground(new Color(51, 51, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblBatchTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatchTransferMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBatchTransferMouseClicked

    private void lblBatchTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatchTransferMouseEntered
        lblBatchTransfer.setSize(180, 210);
        lblTransfer.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBatchTransferMouseEntered

    private void lblBatchTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatchTransferMouseExited
        lblBatchTransfer.setSize(170, 200);
        lblTransfer.setForeground(new Color(51, 51, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBatchTransferMouseExited

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        lblLogOut.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-shutdown-52.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        lblLogOut.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-shutdown-52.png"));
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        lblLogOut.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-shutdown-48.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogOutMouseExited

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        lblSettings.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-services-52.png"));
// TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited
        lblSettings.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-services-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseExited

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        lblSettings.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\Project\\Ijse Billing System\\src\\lk\\ijse\\billingSystem\\resources\\icons8-services-52.png"));
        pnlNewAdmin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        txtPassword.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        txtConfirmPassword.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        btnAdd.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//        System.out.println(txtPassword.getText());
//        AdminDTO adminDTO = new AdminDTO(txtName.getText(),
//            txtPassword.getText());
//        System.out.println("2");
//        try {
//            boolean result = false;
//            if (txtPassword.getText().equals(txtConfirmPassword.getText())) {
//                result = AdminController.addAdmin(adminDTO);
//                System.out.println("admin");
//                result = true;
//
//                if (result) {
//                    JOptionPane.showMessageDialog(this, "Admin added successfully");
//                    txtName.setText("");
//                    txtPassword.setText("");
//                    txtConfirmPassword.setText("");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Admin not added successfully");
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Wrong confirm Password");
//                txtConfirmPassword.setText("");
//                txtPassword.setText("");
//            }
//
//        } catch (Exception ex) {
//            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
        /*
         } else {

         }
         */
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void lblCloseAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAMouseClicked
        pnlNewAdmin.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseAMouseClicked

    private void lblCloseAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAMouseEntered
        lblCloseA.setSize(40, 40);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseAMouseEntered

    private void lblIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncomeMouseClicked
        Reports r=new Reports();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_lblIncomeMouseClicked

    private void lblIncomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncomeMouseEntered
        lblIncome.setSize(200, 90);
        lblIncome.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIncomeMouseEntered

    private void lblIncomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncomeMouseExited
        lblIncome.setSize(190, 80);
        lblIncome.setForeground(new Color(51, 51, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIncomeMouseExited

    private void lblPendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseClicked
        this.setVisible(false);
        VeiwPayments v = new VeiwPayments();
        v.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPendingMouseClicked

    private void lblPendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseEntered
        lblPending.setSize(210, 90);
        lblPending.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPendingMouseEntered

    private void lblPendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseExited
        lblPending.setSize(200, 80);
        lblPending.setForeground(new Color(51, 51, 255));
// TODO add your handling code here:
    }//GEN-LAST:event_lblPendingMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBatchTransfer;
    private javax.swing.JLabel lblCloseA;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblRName;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblTransfer;
    private javax.swing.JPanel pnlNewAdmin;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
