/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.billingSystem.view;

import edu.ijse.billingSystem.validation.Validation;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import lk.ijse.billingSystem.controller.ControllerFactory;
import lk.ijse.billingSystem.controller.custom.BatchController;
import lk.ijse.billingSystem.controller.custom.CourseController;
import lk.ijse.billingSystem.controller.custom.RegistrationController;
import lk.ijse.billingSystem.controller.custom.StudentController;
import lk.ijse.billingSystem.dto.BatchDTO;
import lk.ijse.billingSystem.dto.CourseDTO;
import lk.ijse.billingSystem.dto.Reg_CourseDTO;
import lk.ijse.billingSystem.dto.RegistrationDTO;
import lk.ijse.billingSystem.dto.StudentDTO;
import lk.ijse.billingSystem.id.IdGenarator;


/**
 *
 * @author DEll
 */
public class RegistrationForm extends javax.swing.JFrame {

    RegistrationController registrationController = (RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
    BatchController batchController = (BatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BATCH);
    CourseController courseController = (CourseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.COURSE);
    StudentController studentController=(StudentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.STUDENT);
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        loadDate();
        loadTime();
        loadCourses();
        //loadIds();
        cmbCourse.setSelectedIndex(-1);
        txtCid.setText("");
        textField();
        txtNbt.setEditable(false);
        txtAmount.setEditable(false);
        txtRegNo.setEditable(false);
        txtRegFee.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroupGender = new javax.swing.ButtonGroup();
        rbtnGroupLevel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRegNo = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnFemale = new javax.swing.JRadioButton();
        btnMale = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtRegFee = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNbt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        lblHome = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbBranch = new javax.swing.JComboBox();
        cmbCourse = new javax.swing.JComboBox();
        btnOL = new javax.swing.JRadioButton();
        btnMaster = new javax.swing.JRadioButton();
        btnDegree = new javax.swing.JRadioButton();
        btnDiploma = new javax.swing.JRadioButton();
        btnAL = new javax.swing.JRadioButton();
        txtBid = new javax.swing.JTextField();
        txtCid = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtEduLevel = new javax.swing.JTextField();
        txtRid = new javax.swing.JTextField();
        txtBatchName = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txtReceived = new javax.swing.JTextField();
        txtAmount2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        txtBalance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 193, 161));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Registration");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));

        txtAddress.setBorder(null);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 440, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Telephone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 30));

        txtContact.setBorder(null);
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, 30));

        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 310, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("School");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 140, 30));

        txtSchool.setBorder(null);
        jPanel1.add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 300, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Higher education Level");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Batch");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 120, 30));

        btnPayment.setBackground(new java.awt.Color(102, 255, 102));
        btnPayment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPayment.setText(">>>Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 110, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 370, 10));

        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 370, 30));

        txtNic.setBorder(null);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        jPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 160, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("NIC");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Registration No");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 120, 30));

        txtRegNo.setBorder(null);
        txtRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 120, 30));

        btnRegister.setBackground(new java.awt.Color(102, 102, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        rbtnGroupGender.add(btnFemale);
        btnFemale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFemaleMouseClicked(evt);
            }
        });
        jPanel1.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        rbtnGroupGender.add(btnMale);
        btnMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMale.setText("Male");
        btnMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaleMouseClicked(evt);
            }
        });
        jPanel1.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 162, 40, 430));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Registration Fee");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 120, 30));

        txtRegFee.setBorder(null);
        jPanel1.add(txtRegFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 140, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("nbt");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 120, 30));

        txtNbt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNbt.setBorder(null);
        jPanel1.add(txtNbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Amount");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 120, 30));

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAmount.setBorder(null);
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 140, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Course");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 120, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 440, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 310, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 300, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 120, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 140, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 140, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, -1, -1));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, -1, -1));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 140, -1));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-home-55.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 50));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-close-window-48.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-minimize-window-48.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 40));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 30));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Branch");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 120, 30));

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Panadura", "Galle" }));
        cmbBranch.setSelectedIndex(-1);
        cmbBranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBranchItemStateChanged(evt);
            }
        });
        cmbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBranchActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 110, 30));

        cmbCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCourseItemStateChanged(evt);
            }
        });
        cmbCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCourseMouseClicked(evt);
            }
        });
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 160, 30));

        rbtnGroupLevel.add(btnOL);
        btnOL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOL.setText("O/L");
        btnOL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOLMouseClicked(evt);
            }
        });
        btnOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOLActionPerformed(evt);
            }
        });
        jPanel1.add(btnOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        rbtnGroupLevel.add(btnMaster);
        btnMaster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMaster.setText("Master");
        btnMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterMouseClicked(evt);
            }
        });
        jPanel1.add(btnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        rbtnGroupLevel.add(btnDegree);
        btnDegree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDegree.setText("Degree");
        btnDegree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDegreeMouseClicked(evt);
            }
        });
        jPanel1.add(btnDegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, -1, -1));

        rbtnGroupLevel.add(btnDiploma);
        btnDiploma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDiploma.setText("Diploma");
        btnDiploma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiplomaMouseClicked(evt);
            }
        });
        jPanel1.add(btnDiploma, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        rbtnGroupLevel.add(btnAL);
        btnAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAL.setText("A/L");
        btnAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnALMouseClicked(evt);
            }
        });
        jPanel1.add(btnAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, -1, -1));
        jPanel1.add(txtBid, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 40, 30));
        jPanel1.add(txtCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 40, 30));
        jPanel1.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 90, -1));
        jPanel1.add(txtEduLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 70, -1));
        jPanel1.add(txtRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 70, -1));

        txtBatchName.setBorder(null);
        txtBatchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtBatchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 120, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 120, 30));

        txtReceived.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtReceived.setBorder(null);
        txtReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceivedActionPerformed(evt);
            }
        });
        jPanel1.add(txtReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 140, 30));

        txtAmount2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAmount2.setBorder(null);
        txtAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmount2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 140, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Received Amount");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 120, 30));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 140, -1));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 590, 140, -1));

        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBalance.setBorder(null);
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 140, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Balance");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        PaymentsForm p= new PaymentsForm();
        this.setVisible(false);
        p.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtContact.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-55.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));
        Main m = new Main();
        this.setVisible(false);
        m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
        this.setExtendedState(ICONIFIED);
// TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit?");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
//        //Date date1 = DateChooserDateOfBirth.getDate();
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        //String formatDate = dateFormat.format(date1);
//        //ButtonModel gender=rbtnGroupGender.getSelection();
//        //gender.getN
//        //System.out.println(formatDate);
//        System.out.println(txtName.getText());
//        System.out.println(txtNic.getText());
//        System.out.println(txtAddress.getText());
//        System.out.println(txtContact.getText());
//        System.out.println(txtEmail.getText());
//        System.out.println(txtGender.getText());
//        System.out.println(txtSchool.getText());
//        System.out.println(txtEduLevel.getText());
//        System.out.println(txtRegNo.getText());
//
//        System.out.println(txtRegNo.getText());
//        System.out.println(txtBid.getText());
//        System.out.println(txtCid.getText());
//
//        //StudentDTO studentDTO = new StudentDTO(txtName.getText(), txtNic.getText(), txtAddress.getText(), txtContact.getText(), txtEmail.getText(), formatDate, txtGender.getText(), txtSchool.getText(), txtEduLevel.getText(), txtRegNo.getText());
//        RegistrationDTO registrationDTO = new RegistrationDTO(txtRegNo.getText(), lblDate.getText(), Double.parseDouble(txtRegFee.getText()), Double.parseDouble(txtNbt.getText()));
//        Reg_CourseDTO reg_CourseDTO = new Reg_CourseDTO(txtRegNo.getText(), Integer.parseInt(txtCid.getText()), Integer.parseInt(txtBid.getText()));
//        //boolean added = registrationController.addRegistration(studentDTO, registrationDTO, reg_CourseDTO);
//
//        if (added) {
//            try {
//                JOptionPane.showMessageDialog(this, "Registration has been Success");
//                txtRegNo.setText(IdGenarator.getNewID("Registration", "RID", "r"));
//                clearText();
//                             } catch (IOException ex) {
//                Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
//            } 
//            
//        } else {
//            JOptionPane.showMessageDialog(this, "Registration hasn't been Success");
//            txtAddress.setText("");
//        }

// TODO add your handling code here:

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOLActionPerformed

    private void btnMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaleMouseClicked
        getGender();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaleMouseClicked

    private void btnFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFemaleMouseClicked
        getGender();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFemaleMouseClicked

    private void btnMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterMouseClicked
        getEduLevel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterMouseClicked

    private void btnDegreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDegreeMouseClicked
        getEduLevel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDegreeMouseClicked

    private void btnDiplomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiplomaMouseClicked
        getEduLevel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiplomaMouseClicked

    private void btnALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnALMouseClicked
        getEduLevel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnALMouseClicked

    private void btnOLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOLMouseClicked
        getEduLevel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOLMouseClicked

    private void cmbCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCourseItemStateChanged

    }//GEN-LAST:event_cmbCourseItemStateChanged

    private void cmbBranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBranchItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBranchItemStateChanged

    private void cmbCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseMouseClicked

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed
//        String branch = (String) cmbBranch.getSelectedItem();
//        int cid = Integer.parseInt(txtCid.getText());
//        loadBatches(branch, cid);
//        loadDetails();
        // TODO add your handling code here:
        cmbCourse.setSelectedIndex(-1);
        txtBatchName.setText("");
        txtRegFee.setText("");
        txtRegNo.setText("");
        txtNbt.setText("");
        txtAmount.setText("");
    }//GEN-LAST:event_cmbBranchActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        try {
            txtCid.setText("");
            String course = (String) cmbCourse.getSelectedItem();
            if (course != null) {
                CourseDTO courseDTO = courseController.searchCourse(course);
                txtCid.setText(Integer.toString(courseDTO.getCid()));
                String branch = (String) cmbBranch.getSelectedItem();
                int cid = Integer.parseInt(txtCid.getText());
                if (cid != 0 & branch != null) {
                    loadBatches(branch, cid);
                    loadDetails();
                    txtRegNo.setText(IdGenarator.getNewID("Registration", "RID", "r"));
                }
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void txtBatchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchNameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchNameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        txtEmail.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactKeyPressed

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased
        Validation.phoneNumber(txtContact);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactKeyReleased

    private void txtReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceivedActionPerformed
       double received=Double.parseDouble(txtReceived.getText());
       double amount=Double.parseDouble(txtAmount.getText());
       txtBalance.setText(Double.toString(received-amount));
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceivedActionPerformed

    private void txtAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount2ActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        txtNic.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        try {
            String  nic = txtNic.getText();
            StudentDTO studentDTO = studentController.searchStudent(nic);
            if (studentDTO!=null) {
                JOptionPane.showMessageDialog(this, "Student has been registered before");
                txtNic.setText("");
            }else{
                txtAddress.requestFocus();
            }
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAL;
    private javax.swing.JRadioButton btnDegree;
    private javax.swing.JRadioButton btnDiploma;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnMaster;
    private javax.swing.JRadioButton btnOL;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox cmbBranch;
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTime;
    private javax.swing.ButtonGroup rbtnGroupGender;
    private javax.swing.ButtonGroup rbtnGroupLevel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmount2;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBatchName;
    private javax.swing.JTextField txtBid;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEduLevel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNbt;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtReceived;
    private javax.swing.JTextField txtRegFee;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextField txtRid;
    private javax.swing.JTextField txtSchool;
    // End of variables declaration//GEN-END:variables

    private void loadDate() {
        Date date = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        String dateFormat = sf.format(date);
        lblDate.setText(dateFormat);
    }

    private void loadTime() {
        new javax.swing.Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss ");
                String DateFormat = df.format(d1);
                lblTime.setText(DateFormat);
            }
        }).start();
    }

    public String getGender() {
        if (btnMale.isSelected()) {
            txtGender.setText("Male");
            return "Male";
        } else if (btnFemale.isSelected()) {
            txtGender.setText("Female");
            return "Female";
        } else {
            return null;
        }
    }

    public String getEduLevel() {
        if (btnMaster.isSelected()) {
            txtEduLevel.setText("Master");
            return "Master";
        } else if (btnDegree.isSelected()) {
            txtEduLevel.setText("Degree");
            return "Degree";
        } else if (btnDiploma.isSelected()) {
            txtEduLevel.setText("Diploma");
            return "Diploma";
        } else if (btnAL.isSelected()) {
            txtEduLevel.setText("A/L");
            return "A/L";
        } else if (btnOL.isSelected()) {
            txtEduLevel.setText("O/L");
            return "O/L";
        } else {
            return null;
        }
    }

    public void clearText() {
        txtAddress.setText("");
        txtBid.setText("");
        txtAddress.setText("");
        txtCid.setText("");
        txtContact.setText("");
        txtEduLevel.setText("");
        txtEduLevel.setText("");
        txtEmail.setText("");
        txtGender.setText("");
        txtName.setText("");
        txtNbt.setText("");
        txtNic.setText("");
        txtRegFee.setText("");
        txtRegNo.setText("");
        txtSchool.setText("");
        txtAmount.setText("");
        txtBatchName.setText("");
        txtRid.setText("");
        txtGender.setText("");
        txtEduLevel.setText("");
        rbtnGroupGender.clearSelection();
        rbtnGroupLevel.clearSelection();
        cmbBranch.setSelectedIndex(-1);
        cmbCourse.setSelectedIndex(-1);
        txtBalance.setText("");
        txtReceived.setText("");
    }

    void loadBatches(String branch, int cid) {
        // cmbBatch.removeAllItems();
        try {
            BatchDTO batchDTO = batchController.getBatch(branch, cid);
            if (batchDTO!=null) {
                txtBatchName.setText(batchDTO.getName());
            txtBid.setText(Integer.toString(batchDTO.getBid()));
            System.out.println(batchDTO.getBid());
            }else{
                JOptionPane.showMessageDialog(this, "No such Batch");
            }
            
//            ArrayList<BatchDTO> alBatches = batchController.getBatches(branch, cid);
//            for (BatchDTO Batch : alBatches) {
//                cmbBatch.addItem(Batch.getName());
//                //cmbBatch.setSelectedIndex(-1);
//            }

        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCourses() {
        cmbCourse.removeAllItems();
        try {
            ArrayList<CourseDTO> alCourses = courseController.getCourses();
            for (CourseDTO course : alCourses) {
                cmbCourse.addItem(course.getName());

            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbCourse.setSelectedIndex(-1);
        txtCid.setText("");
    }

    private void loadIds() {
        try {
            txtRegNo.setText(IdGenarator.getNewID("Registration", "RID", "r"));
        } catch (IOException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void loadDetails() {
        String course = (String) cmbCourse.getSelectedItem();
        if (course != null) {
            try {
                CourseDTO courseDTO = courseController.searchCourse(course);
                txtRegFee.setText(Double.toString(courseDTO.getRegFee()));
                double nbt = Double.parseDouble(courseDTO.getTax());
                double regFee = courseDTO.getRegFee();
                double tax = regFee / 100 * nbt;
                int cid = Integer.parseInt(txtCid.getText());
                txtNbt.setText(Double.toString(tax));
                txtAmount.setText(Double.toString(regFee + tax));
            } catch (Exception ex) {
                Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void textField() {
        txtBid.setVisible(false);
        txtCid.setVisible(false);
        txtRid.setVisible(false);
        txtGender.setVisible(false);
        txtEduLevel.setVisible(false);
    }

}
