/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.billingSystem.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.billingSystem.db.DBConnection;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DEll
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        loadDate();
        loadTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPayment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 193, 161));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Reports");
        jLabel1.setOpaque(true);
        pnlPayment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 80));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-home-55.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        pnlPayment.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 50));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-minimize-window-48.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        pnlPayment.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 40));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/billingSystem/resources/icons8-close-window-48.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        pnlPayment.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 51, 102));
        pnlPayment.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 30));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 51, 102));
        pnlPayment.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Monthly Income");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlPayment.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 190, 50));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Daily Income");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlPayment.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 183, 190, 50));

        getContentPane().add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));
        Main m = new Main();
        this.setVisible(false);
        m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-64.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-home-55.png"));

        // TODO add your handling code here:
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
        this.setExtendedState(ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-55.png"));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-minimize-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit?");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-55.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon("J:\\3rd semester\\Niroth Sir\\4\\images\\icons8-close-window-48.png"));
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/lk/ijse/billingSystem/report/Daily.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
            // TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/lk/ijse/billingSystem/report/Monthly Income.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
            // TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlPayment;
    // End of variables declaration//GEN-END:variables

    private void loadDate() {
        Date date = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        String dateFormat = sf.format(date);
        lblDate.setText(dateFormat);
    }

    private void loadTime() {
        new javax.swing.Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss ");
                String DateFormat = df.format(d1);
                lblTime.setText(DateFormat);
            }
        }).start();
    }
}
